package models

// All returns every model, in dependency order, for AutoMigrate.
func All() []any {
	return []any{
		&Tenant{},
		&TenantSearchableKey{},
		&TenantEmailConfig{},
		&TenantEmailDomain{},
		&TenantPushConfig{},
		&APIKey{},
		&AdminUser{},
		&RoleAssignment{},
		&AdminSession{},
		&SigningKey{},
		&Contact{},
		&ContactMeta{},
		&Conversation{},
		&ConversationMember{},
		&Assignment{},
		&Message{},
		&MessageAttachment{},
		&EmailThread{},
		&Upload{},
		&ReadReceipt{},
		&PushToken{},
		&WebhookEndpoint{},
		&WebhookEvent{},
		&Outbox{},
		&PushOutbox{},
		&WebhookDelivery{},
		&ConversationArchive{},
		&Brand{},
		&JobLease{},
		&EmailIngest{},
		&TranslationProject{},
		&TranslationProjectLocale{},
		&TranslationKey{},
		&TranslationOverride{},
		&TranslationRelease{},
		&TranslationBundle{},
	}
}
